### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by Forgi4G**
Ignoring .git and .idea so when I do actually contribute, I don't push .idea or .git to the repo

### CODE REVIEW

**Comment by ItsRauf** [comment]
pls no merge to master. I have so much unfinished code that isn't even in the dev branch yet

**Comment by Forgi4G** [comment]
I guess we can wait, I'd totally like to contribute to unfinished code.

**Comment by Forgi4G** [comment]
I wonder if you can rebase it, so that patch-1 is merged into dev instead of dev being merged the other way.

**Comment by ent3r** [comment]
i just have to ask... why gitignore .git?

**Comment by Forgi4G** [comment]
The `.git` folder generally should be ignored, also good if I end up cloning repo the and then pushing changes. Don't want to push the `.git` folder really.

**Comment by ItsRauf** [comment]
I just use the default nodejs gitignore template and add stuff I need to not push

**Comment by Forgi4G** [comment]
Since this PR tries to merge dev in patch-1, should I close this and create a new PR where patch-1 is merged into dev instead of the other way?

**Comment by ent3r** [comment]
> The .git folder generally should be ignored, also good if I end up cloning repo the and then pushing changes. Don't want to push the .git folder really.

Am I missing something? The `.git` folder is the folder that contains all the history and data of the repo. It can't get added, the `git` CLI ignores it. There's nothing there to ignore. Please correct me if I'm wrong.

**Comment by Forgi4G** [comment]
I mean, if there is no problem ignoring it then there is no need to discuss the the `git` folder being ignored really.

**Pull request closed without merging**
